# ETL Pipeline

Load the raw CSVs, clean and type-cast the data, then export the processed files to `data/processed`.

## Setup

Set the working directory to the project root and define the raw and processed data paths.

In [1]:
import os
current_dir = os.getcwd()
current_dir

'/Users/stephenbeese/GitHub/play-sports-network-technical-exercise/jupyter_notebook'

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'/Users/stephenbeese/GitHub/play-sports-network-technical-exercise'

In [4]:
# Set the file path for the raw data
raw_data_dir = os.path.join(current_dir, 'data/raw')

# Set the file path for the processed data
processed_data_dir = os.path.join(current_dir, 'data/processed')

# Print file paths
print("Raw data directory:", raw_data_dir)
print("Clean data directory:", processed_data_dir)

Raw data directory: /Users/stephenbeese/GitHub/play-sports-network-technical-exercise/data/raw
Clean data directory: /Users/stephenbeese/GitHub/play-sports-network-technical-exercise/data/processed

# Imports

In [5]:
import pandas as pd

# Posts

Load `posts.csv`, cast `published_at_date` to a datetime, check for nulls and duplicates, then export the cleaned data.

In [6]:
df_posts = pd.read_csv(os.path.join(raw_data_dir, 'posts.csv'))
df_posts.head()

,post_id,video_id,account_name,published_at_date,video_url,video_type,title,text,video_length,thumbnail_url
0,UC7Txz5nUDD14vCdNSU_JydQxmu1jJgyV4I,xmu1jJgyV4I,EMBN,2025-11-09,https://www.youtube.com/watch?v=xmu1jJgyV4I,Shorts,This Race Was Awesome!⁠,In association with ⁠\n🤝Bosch⁠\n.⁠\n#EMBN #AD ...,79000,https://i.ytimg.com/vi/xmu1jJgyV4I/sddefault.jpg
1,UC7Txz5nUDD14vCdNSU_JydQtm-JUK2Avkw,tm-JUK2Avkw,EMBN,2025-10-27,https://www.youtube.com/watch?v=tm-JUK2Avkw,Shorts,This Is What Its All About!,In association with \n🤝 Bosch\n.\n#EMBN #AD #E...,70000,https://i.ytimg.com/vi/tm-JUK2Avkw/sddefault.jpg
2,UC7Txz5nUDD14vCdNSU_JydQZVbfaP7FtuI,ZVbfaP7FtuI,EMBN,2025-11-14,https://www.youtube.com/watch?v=ZVbfaP7FtuI,Long Form,The Very Best Electric Mountain Bikes For 2026,What will be the hottest eBike of 2026? In thi...,1505000,https://i.ytimg.com/vi/ZVbfaP7FtuI/sddefault.jpg
3,UC7Txz5nUDD14vCdNSU_JydQBjbCiqMx62s,BjbCiqMx62s,EMBN,2025-11-25,https://www.youtube.com/watch?v=BjbCiqMx62s,Shorts,"First Trail Of The Day, First CRASH Of The Day...",📺 Full Video LIVE NOW on our #YouTube! 🎬\n🔎The...,74000,https://i.ytimg.com/vi/BjbCiqMx62s/sddefault.jpg
4,UC7Txz5nUDD14vCdNSU_JydQNjQFTPXwDG0,NjQFTPXwDG0,EMBN,2025-10-06,https://www.youtube.com/watch?v=NjQFTPXwDG0,Shorts,More Power For Longer! MAHLE Shake Up The eBik...,More Power For Longer! MAHLE Shake Up The eBik...,82000,https://i.ytimg.com/vi/NjQFTPXwDG0/sddefault.jpg

In [7]:
df_posts.info()

<class 'pandas.DataFrame'>
RangeIndex: 2326 entries, 0 to 2325
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   post_id            2326 non-null   str
 1   video_id           2326 non-null   str
 2   account_name       2326 non-null   str
 3   published_at_date  2326 non-null   str
 4   video_url          2326 non-null   str
 5   video_type         2326 non-null   str
 6   title              2326 non-null   str
 7   text               2316 non-null   str
 8   video_length       2326 non-null   int64
 9   thumbnail_url      2326 non-null   str
dtypes: int64(1), str(9)
memory usage: 181.8 KB

In [8]:
# convert published_at_date to datetime (source format is ISO YYYY-MM-DD)
df_posts['published_at_date'] = pd.to_datetime(df_posts['published_at_date'], format='%Y-%m-%d')

df_posts.info()

<class 'pandas.DataFrame'>
RangeIndex: 2326 entries, 0 to 2325
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   post_id            2326 non-null   str
 1   video_id           2326 non-null   str
 2   account_name       2326 non-null   str
 3   published_at_date  2326 non-null   datetime64[us]
 4   video_url          2326 non-null   str
 5   video_type         2326 non-null   str
 6   title              2326 non-null   str
 7   text               2316 non-null   str
 8   video_length       2326 non-null   int64
 9   thumbnail_url      2326 non-null   str
dtypes: datetime64[us](1), int64(1), str(8)
memory usage: 181.8 KB

In [9]:
df_posts.shape

(2326, 10)

In [10]:
df_posts.isnull().sum()

post_id               0
video_id              0
account_name          0
published_at_date     0
video_url             0
video_type            0
title                 0
text                 10
video_length          0
thumbnail_url         0
dtype: int64

In [11]:
df_posts.duplicated().sum()

np.int64(0)

In [12]:
df_posts.head()

,post_id,video_id,account_name,published_at_date,video_url,video_type,title,text,video_length,thumbnail_url
0,UC7Txz5nUDD14vCdNSU_JydQxmu1jJgyV4I,xmu1jJgyV4I,EMBN,2025-11-09,https://www.youtube.com/watch?v=xmu1jJgyV4I,Shorts,This Race Was Awesome!⁠,In association with ⁠\n🤝Bosch⁠\n.⁠\n#EMBN #AD ...,79000,https://i.ytimg.com/vi/xmu1jJgyV4I/sddefault.jpg
1,UC7Txz5nUDD14vCdNSU_JydQtm-JUK2Avkw,tm-JUK2Avkw,EMBN,2025-10-27,https://www.youtube.com/watch?v=tm-JUK2Avkw,Shorts,This Is What Its All About!,In association with \n🤝 Bosch\n.\n#EMBN #AD #E...,70000,https://i.ytimg.com/vi/tm-JUK2Avkw/sddefault.jpg
2,UC7Txz5nUDD14vCdNSU_JydQZVbfaP7FtuI,ZVbfaP7FtuI,EMBN,2025-11-14,https://www.youtube.com/watch?v=ZVbfaP7FtuI,Long Form,The Very Best Electric Mountain Bikes For 2026,What will be the hottest eBike of 2026? In thi...,1505000,https://i.ytimg.com/vi/ZVbfaP7FtuI/sddefault.jpg
3,UC7Txz5nUDD14vCdNSU_JydQBjbCiqMx62s,BjbCiqMx62s,EMBN,2025-11-25,https://www.youtube.com/watch?v=BjbCiqMx62s,Shorts,"First Trail Of The Day, First CRASH Of The Day...",📺 Full Video LIVE NOW on our #YouTube! 🎬\n🔎The...,74000,https://i.ytimg.com/vi/BjbCiqMx62s/sddefault.jpg
4,UC7Txz5nUDD14vCdNSU_JydQNjQFTPXwDG0,NjQFTPXwDG0,EMBN,2025-10-06,https://www.youtube.com/watch?v=NjQFTPXwDG0,Shorts,More Power For Longer! MAHLE Shake Up The eBik...,More Power For Longer! MAHLE Shake Up The eBik...,82000,https://i.ytimg.com/vi/NjQFTPXwDG0/sddefault.jpg

In [13]:
df_posts_cleaned = df_posts.copy()
df_posts_cleaned.to_csv(os.path.join(processed_data_dir, 'posts_cleaned.csv'), index=False)

# Post Stats

Load `poststats.csv`, cast `data_date` to a datetime and `views`/`watchtime` to integers (stripping thousands separators), check for nulls and duplicates, then export the cleaned data.

In [14]:
df_post_stats = pd.read_csv(os.path.join(raw_data_dir, 'poststats.csv'))
df_post_stats.head()

      video_id   data_date  likes  comments  shares views watchtime
0  4YslQKeVpHQ  11/12/2025      0         0       0     1         0
1  6A86YrFwvbw  11/12/2025      0         0       0     1         0
2  2ceH-wbbKT0  11/12/2025      0         0       0    24        10
3  5LG-Sxz7MrQ  11/12/2025      3         0       0   131        59
4  4A1SXMKPTn0  11/12/2025      0         0       0     5        31

In [15]:
df_post_stats.info()

<class 'pandas.DataFrame'>
RangeIndex: 187974 entries, 0 to 187973
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   video_id   187974 non-null  str
 1   data_date  187974 non-null  str
 2   likes      187974 non-null  int64
 3   comments   187974 non-null  int64
 4   shares     187974 non-null  int64
 5   views      187974 non-null  str
 6   watchtime  187974 non-null  str
dtypes: int64(3), str(4)
memory usage: 10.0 MB

In [16]:
# convert data_date to datetime DD/MM/YYYY
df_post_stats['data_date'] = pd.to_datetime(df_post_stats['data_date'], format='%d/%m/%Y')

# convert views to integer and strip commas
df_post_stats['views'] = df_post_stats['views'].astype(str).str.replace(',', '', regex=False).astype(int)

# convert watchtime to integer and strip commas
df_post_stats['watchtime'] = df_post_stats['watchtime'].astype(str).str.replace(',', '', regex=False).astype(int)

df_post_stats.info()

<class 'pandas.DataFrame'>
RangeIndex: 187974 entries, 0 to 187973
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   video_id   187974 non-null  str
 1   data_date  187974 non-null  datetime64[us]
 2   likes      187974 non-null  int64
 3   comments   187974 non-null  int64
 4   shares     187974 non-null  int64
 5   views      187974 non-null  int64
 6   watchtime  187974 non-null  int64
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 10.0 MB

In [17]:
df_post_stats.isnull().sum()

video_id     0
data_date    0
likes        0
comments     0
shares       0
views        0
watchtime    0
dtype: int64

In [18]:
df_post_stats.duplicated().sum()

np.int64(0)

In [19]:
df_post_stats.head()

      video_id  data_date  likes  comments  shares  views  watchtime
0  4YslQKeVpHQ 2025-12-11      0         0       0      1          0
1  6A86YrFwvbw 2025-12-11      0         0       0      1          0
2  2ceH-wbbKT0 2025-12-11      0         0       0     24         10
3  5LG-Sxz7MrQ 2025-12-11      3         0       0    131         59
4  4A1SXMKPTn0 2025-12-11      0         0       0      5         31

In [21]:
df_post_stats_cleaned = df_post_stats.copy()
df_post_stats_cleaned.to_csv(os.path.join(processed_data_dir, 'poststats_cleaned.csv'), index=False)